apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
  labels:
    name: greeting
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
      - name: greeting
        image: {{ .Values.greeting.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: "http"
        - containerPort: {{ .Values.service.internalDebugPort }}
          name: "debug"
